//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamilyTreeEntities : DbContext
    {
        public FamilyTreeEntities()
            : base("name=FamilyTreeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLevel> AccessLevel { get; set; }
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<CharacterBiography> CharacterBiography { get; set; }
        public virtual DbSet<CharacterBirthCountry> CharacterBirthCountry { get; set; }
        public virtual DbSet<CharacterBirthDate> CharacterBirthDate { get; set; }
        public virtual DbSet<CharacterBirthPlace> CharacterBirthPlace { get; set; }
        public virtual DbSet<CharacterDeathCountry> CharacterDeathCountry { get; set; }
        public virtual DbSet<CharacterDeathDate> CharacterDeathDate { get; set; }
        public virtual DbSet<CharacterDeathPlace> CharacterDeathPlace { get; set; }
        public virtual DbSet<CharacterFirstName> CharacterFirstName { get; set; }
        public virtual DbSet<CharacterLastName> CharacterLastName { get; set; }
        public virtual DbSet<CharacterLivingCountry> CharacterLivingCountry { get; set; }
        public virtual DbSet<CharacterLivingPlace> CharacterLivingPlace { get; set; }
        public virtual DbSet<CharacterNationality> CharacterNationality { get; set; }
        public virtual DbSet<CharacterPhoto> CharacterPhoto { get; set; }
        public virtual DbSet<CharacterReligious> CharacterReligious { get; set; }
        public virtual DbSet<CharacterSecondName> CharacterSecondName { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<HouseCharacter> HouseCharacter { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<RelativeCharacter> RelativeCharacter { get; set; }
        public virtual DbSet<RelativeType> RelativeType { get; set; }
        public virtual DbSet<Religious> Religious { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
