//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelativeCharacter
    {
        public int characterId { get; set; }
        public int targetId { get; set; }
        public string type { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Character Character1 { get; set; }
        public virtual RelativeType RelativeType { get; set; }
    }
}
